GET http://localhost:5000/api/projects

####

POST http://localhost:5000/api/projects
Content-Type: application/json

{
    "project_name": "Alex22",
    "project_description": "Alex22",
    "project_completed": false
}