GET http://localhost:5000/api/resources

####

POST http://localhost:5000/api/resources
Content-Type: application/json

{
    "resource_name": "Hell Yeah Brother!!",
    "resource_description": "also known as Jake"
}