GET http://localhost:5000/api/resources

####

POST http://localhost:5000/api/resources
Content-Type: application/json

{
    "resource_name": "Google",
    "resource_description": "American multinational technology company, a subsidiary of Alphabet inc."
}